### ISSUE TITLE
Issue in labeling most recent forecast

### ISSUE THREAD

**Issue by elliottmorris** [elliottevans/election_forecasts#1]
Hey, I've been experimenting with your code to learn R and I notices a slight error in the "#polls_altered_final gives us our final forecasts" section of main.r. 

Specifically, if there is any forecast on the same day, it will label them both as final forecasts and mess up the electoral calculator and plotter for that state's predictions. 

Any idea how I could fix this? 

Thanks!

**Comment by elliottevans** [comment]
Good point! I had updated that so that it essentially averages any state polls/national polls that occur on the same day. I just hadn't pushed it to github yet. I'm actually going to be making lots of changes to that code soon so that it also utilizes national polls.

**Comment by elliottmorris** [comment]
That'll be really cool, looking forward to it!

**Comment by elliottmorris** [comment]
Any idea how I could implement that averaging for some-day polls? Like the new code, but it's a little much for my needs.
